### PR TITLE
add：model manager version

### PR DESCRIPTION
**Pull request by CodingJzy**
When I use multiple model managers, elemental newrequest, the previous key (0) is unchanged, but I am the model manager according to the version. At this moment. Identity cannot be obtained.
image

### CODE REVIEW

**Comment by primalmotion** [comment]
Hi,

thanks for the patch. However, I don't really understand the problem you are trying to solve. Could you elaborate on what is your issue?

**Comment by primalmotion** [comment]
My bad, I understand. This code used to work before, let me dig a bit further on why this changed

**Comment by primalmotion** [comment]
OK, I believe the correct fix is to change `NewRequestFromHTTPRequest` in elemental to get a `map[int]ModelManager`. The code to parse the version is already in here. Then it can pick up what version to use. it should also be added a check to prevent asking for a version out of bounds.

It is also planned to move this parsing of HTTP request into Bahamut later, since it has nothing to do in Elemental.

**Comment by CodingJzy** [comment]
thank you！Will you change it later？Can I close the merge request？

**Comment by primalmotion** [comment]
Hey, I actually started to do it in a PR, but got issues with the elemental API that will need an additional change. Ended up doing mostly what you did, but got integrated a some new suite of tests.

Thanks for pointing this out and working on it!

**Pull request closed without merging**
